interface=wlp44s0
driver=nl80211
ssid=test2k25
country_code=IN
ieee80211d=1
ieee80211n=1
hw_mode=g
channel=5
beacon_int=100
dtim_period=2
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
logger_syslog=0
logger_syslog_level=0
logger_stdout=-1
logger_stdout_level=2
wpa=2
wpa_passphrase=test@123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
